export const DEFAULT_CATEGORIES = [
  {
    name: 'Salary',
    type: 'income' as const,
    icon: 'briefcase',
    color: '#10B981',
    is_default: true,
  },
  {
    name: 'Freelance',
    type: 'income' as const,
    icon: 'laptop',
    color: '#3B82F6',
    is_default: true,
  },
  {
    name: 'Investments',
    type: 'income' as const,
    icon: 'trending-up',
    color: '#8B5CF6',
    is_default: true,
  },
  {
    name: 'Food & Dining',
    type: 'expense' as const,
    icon: 'utensils',
    color: '#F59E0B',
    is_default: true,
  },
  {
    name: 'Transport',
    type: 'expense' as const,
    icon: 'car',
    color: '#EF4444',
    is_default: true,
  },
  {
    name: 'Shopping',
    type: 'expense' as const,
    icon: 'shopping-bag',
    color: '#EC4899',
    is_default: true,
  },
  {
    name: 'Bills & Utilities',
    type: 'expense' as const,
    icon: 'receipt',
    color: '#6366F1',
    is_default: true,
  },
  {
    name: 'Healthcare',
    type: 'expense' as const,
    icon: 'heart',
    color: '#14B8A6',
    is_default: true,
  },
  {
    name: 'Entertainment',
    type: 'expense' as const,
    icon: 'film',
    color: '#F97316',
    is_default: true,
  },
  {
    name: 'Other',
    type: 'expense' as const,
    icon: 'tag',
    color: '#6B7280',
    is_default: true,
  },
];
