export const ROUTES = {
  home: '/',
  auth: '/auth',
  dashboard: '/app/dashboard',
  transactions: '/app/transactions',
  transaction: (id: string) => `/app/transactions/${id}`,
  transactionNew: '/app/transactions/new',
  accounts: '/app/accounts',
  account: (id: string) => `/app/accounts/${id}`,
  creditCards: '/app/credit-cards',
  creditCard: (id: string) => `/app/credit-cards/${id}`,
  budgets: '/app/budgets',
  goals: '/app/goals',
  goal: (id: string) => `/app/goals/${id}`,
  loans: '/app/loans',
  loan: (id: string) => `/app/loans/${id}`,
  investments: '/app/investments',
  investment: (id: string) => `/app/investments/${id}`,
  recurring: '/app/recurring',
  documents: '/app/documents',
  document: (id: string) => `/app/documents/${id}`,
  analytics: '/app/analytics',
  settings: '/app/settings',
} as const;
